name: Update the Image Tag and Deploy
on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image tag version'
        required: true

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Update the Image Tag and Deploy
      run: |
        echo "ImageTag : ${{ github.event.inputs.imageTag }}"
        python deploy.py ${{ github.event.inputs.imageTag }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
