name: Update the Image Tag and Deploy
on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image tag version to Deploy'
        required: true

jobs:
  update_image_tag_and_deploy:
    name: Update Image Tag to - ${{ github.event.inputs.imageTag }} and Deploy
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Install Python Dependencies
      run: pip install -r requirements.txt

    - name: Update the Image Tag and Deploy
      run: |
        echo "ImageTag : ${{ github.event.inputs.imageTag }}"
        python deploy.py ${{ github.event.inputs.imageTag }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go Environment
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.17.0'

    - name: Download Go Modules
      working-directory: test
      run: go mod download

    - name: Pull kubeconfig
      working-directory: test
      run: |
        mkdir kubeconf
        echo "$KUBE_CONFIG" > kubeconf/kubeconf.conf
        ls -l kubeconf
      env:
        KUBE_CONFIG: ${{ secrets.KUBECONFIG }}

    - name: Run TerraTest
      working-directory: test
      run: go test -v
      env:
        KUBECONFIG: "kubeconf/kubeconf.conf"
        KUBE_HOST: ${{ secrets.KUBE_HOST }}
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
